'use client';
import { useEffect, useState } from 'react'; import { useRouter } from 'next/navigation'; import { Nav } from '@/components/Nav';
const days=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
type Service={id:string;name:string;description:string|null;durationMin:number;status:'ACTIVE'|'INACTIVE'};type Rule={id:string;dayOfWeek:number;startTime:string;endTime:string};type Appt={id:string;customerName:string;customerEmail:string;startAt:string;status:string;service:{name:string}};type Business={name:string;slug:string;contactName:string|null;email:string|null;phone:string|null;timezone:string;enabled:boolean};
export default function Admin(){const router=useRouter();const [tab,setTab]=useState('overview');const [business,setBusiness]=useState<Business|null>(null);const [services,setServices]=useState<Service[]>([]);const [rules,setRules]=useState<Rule[]>([]);const [appts,setAppts]=useState<Appt[]>([]);const [msg,setMsg]=useState('');const [service,setService]=useState({name:'',description:'',durationMin:30});const [rule,setRule]=useState({dayOfWeek:1,startTime:'09:00',endTime:'17:00'});const [status,setStatus]=useState('');
const load=async()=>{const [b,s,a,r]=await Promise.all([fetch('/api/admin/business'),fetch('/api/admin/services'),fetch('/api/admin/appointments'),fetch('/api/admin/availability')]);if([b,s,a,r].some(x=>x.status===401||x.status===403)){router.push('/login');return}setBusiness((await b.json()).business);setServices((await s.json()).services);setAppts((await a.json()).appointments);setRules((await r.json()).availability)};useEffect(()=>{load()},[]);
const createService=async(e:React.FormEvent)=>{e.preventDefault();const r=await fetch('/api/admin/services',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(service)});const d=await r.json();if(!r.ok){setMsg(d.error);return}setService({name:'',description:'',durationMin:30});setMsg('Service created');load()};
const toggleService=async(s:Service)=>{await fetch('/api/admin/services/'+s.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:s.status==='ACTIVE'?'INACTIVE':'ACTIVE'})});load()};
const addRule=async(e:React.FormEvent)=>{e.preventDefault();const r=await fetch('/api/admin/availability',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(rule)});const d=await r.json();if(!r.ok){setMsg(d.error);return}setMsg('Availability added');load()};
const removeRule=async(id:string)=>{await fetch('/api/admin/availability/'+id,{method:'DELETE'});load()};
const updateAppt=async(id:string,newStatus:string)=>{await fetch('/api/admin/appointments/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:newStatus})});load()};
const saveBusiness=async(e:React.FormEvent)=>{e.preventDefault();if(!business)return;const r=await fetch('/api/admin/business',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(business)});const d=await r.json();if(!r.ok){setMsg(d.error);return}setMsg('Profile saved');load()};
return <><Nav title={business?`Bookly · ${business.name}`:'Bookly'}/><main className="dashboard"><div className="container"><div className="dashboard-head"><div><div className="small muted">BUSINESS WORKSPACE</div><h1>{business?.name||'Loading…'}</h1><p className="muted">Configure your business, publish availability and manage bookings.</p></div><a className="btn btn-secondary" href={business?`/book/${business.slug}`:'/'} target="_blank">Open booking page ↗</a></div><div className="tabs">{[['overview','Overview'],['services','Services'],['availability','Availability'],['appointments','Appointments'],['profile','Profile']].map(([k,l])=><button key={k} className={'tab '+(tab===k?'active':'')} onClick={()=>setTab(k)}>{l}</button>)}</div>{msg&&<div className="alert success" style={{marginBottom:16}}>{msg}</div>}
{tab==='overview'&&<div className="grid3"><div className="card"><div className="small muted">ACTIVE SERVICES</div><div className="metric" style={{fontFamily:'Space Grotesk',fontSize:38,fontWeight:700}}>{services.filter(s=>s.status==='ACTIVE').length}</div></div><div className="card"><div className="small muted">BOOKINGS</div><div className="metric" style={{fontFamily:'Space Grotesk',fontSize:38,fontWeight:700}}>{appts.filter(a=>a.status!=='CANCELLED').length}</div></div><div className="card"><div className="small muted">PUBLIC PAGE</div><p style={{marginBottom:14}}>/book/{business?.slug}</p><a className="btn btn-primary" href={business?`/book/${business.slug}`:'#'} target="_blank">Preview</a></div></div>}
{tab==='services'&&<div className="two-col"><form className="card stack" onSubmit={createService}><div><h2 className="section-title">Add service</h2><p className="muted">Only active services are visible to customers.</p></div><div className="field"><label>Name</label><input required value={service.name} onChange={e=>setService({...service,name:e.target.value})}/></div><div className="field"><label>Description</label><textarea value={service.description} onChange={e=>setService({...service,description:e.target.value})}/></div><div className="field"><label>Duration (minutes)</label><input type="number" min="15" max="480" value={service.durationMin} onChange={e=>setService({...service,durationMin:Number(e.target.value)})}/></div><button className="btn btn-primary">Create service</button></form><div className="card"><h2 className="section-title">Services</h2><div className="stack">{services.map(s=><div className="row" key={s.id}><div><b>{s.name}</b><div className="small muted">{s.durationMin} min · {s.description}</div></div><div><span className={'pill '+(s.status==='ACTIVE'?'active':'inactive')}>{s.status}</span> <button className="btn btn-secondary" onClick={()=>toggleService(s)}>{s.status==='ACTIVE'?'Deactivate':'Activate'}</button></div></div>)}</div></div></div>}
{tab==='availability'&&<div className="two-col"><form className="card stack" onSubmit={addRule}><div><h2 className="section-title">Add availability</h2><p className="muted">Weekly rules are interpreted in {business?.timezone}.</p></div><div className="field"><label>Day</label><select value={rule.dayOfWeek} onChange={e=>setRule({...rule,dayOfWeek:Number(e.target.value)})}>{days.map((d,i)=><option value={i} key={d}>{d}</option>)}</select></div><div className="form-grid"><div className="field"><label>Start</label><input type="time" value={rule.startTime} onChange={e=>setRule({...rule,startTime:e.target.value})}/></div><div className="field"><label>End</label><input type="time" value={rule.endTime} onChange={e=>setRule({...rule,endTime:e.target.value})}/></div></div><button className="btn btn-primary">Add rule</button></form><div className="card"><h2 className="section-title">Weekly schedule</h2><div className="days">{days.map((d,i)=><div className="day-card" key={d}><strong>{d.slice(0,3)}</strong>{rules.filter(r=>r.dayOfWeek===i).map(r=><div className="rule" key={r.id}><span>{r.startTime}–{r.endTime}</span><button className="btn btn-danger" onClick={()=>removeRule(r.id)}>×</button></div>)}{!rules.some(r=>r.dayOfWeek===i)&&<div className="small muted" style={{marginTop:10}}>Closed</div>}</div>)}</div></div></div>}
{tab==='appointments'&&<div className="card"><div className="row" style={{marginBottom:14}}><div><h2 className="section-title" style={{marginBottom:4}}>Appointments</h2><p className="muted">Manage the booking lifecycle from confirmation to completion.</p></div><select value={status} onChange={e=>setStatus(e.target.value)} className="field" style={{padding:10}}><option value="">All statuses</option><option>CONFIRMED</option><option>COMPLETED</option><option>CANCELLED</option><option>NO_SHOW</option></select></div><div className="table-wrap"><table className="table"><thead><tr><th>Customer</th><th>Service</th><th>When</th><th>Status</th><th>Action</th></tr></thead><tbody>{appts.filter(a=>!status||a.status===status).map(a=><tr key={a.id}><td><b>{a.customerName}</b><div className="small muted">{a.customerEmail}</div></td><td>{a.service.name}</td><td>{new Date(a.startAt).toLocaleString()}</td><td><span className={'pill '+a.status.toLowerCase()}>{a.status.replace('_',' ')}</span></td><td>{a.status==='CONFIRMED'&&<button className="btn btn-secondary" onClick={()=>updateAppt(a.id,'COMPLETED')}>Complete</button>}</td></tr>)}</tbody></table>{!appts.length&&<div className="empty">No appointments yet. Open the public booking page to create one.</div>}</div></div>}
{tab==='profile'&&business&&<form className="card stack" onSubmit={saveBusiness}><div><h2 className="section-title">Business profile</h2><p className="muted">These details are used by the public booking experience.</p></div><div className="form-grid"><div className="field"><label>Name</label><input value={business.name} onChange={e=>setBusiness({...business,name:e.target.value})}/></div><div className="field"><label>Slug</label><input value={business.slug} disabled/></div><div className="field"><label>Contact name</label><input value={business.contactName||''} onChange={e=>setBusiness({...business,contactName:e.target.value})}/></div><div className="field"><label>Email</label><input type="email" value={business.email||''} onChange={e=>setBusiness({...business,email:e.target.value})}/></div><div className="field"><label>Phone</label><input value={business.phone||''} onChange={e=>setBusiness({...business,phone:e.target.value})}/></div><div className="field"><label>Timezone</label><input value={business.timezone} onChange={e=>setBusiness({...business,timezone:e.target.value})}/></div></div><button className="btn btn-primary">Save profile</button></form>}
</div></main></>}
