'use client';
import { useEffect, useState } from 'react'; import { useParams, useRouter } from 'next/navigation';

type Service={id:string;name:string;description:string|null;durationMin:number};type Slot={start:string;end:string;label:string};
export default function Booking(){const {slug}=useParams<{slug:string}>();const router=useRouter();const [business,setBusiness]=useState<any>(null);const [services,setServices]=useState<Service[]>([]);const [serviceId,setServiceId]=useState('');const [date,setDate]=useState('');const [slots,setSlots]=useState<Slot[]>([]);const [selected,setSelected]=useState<Slot|null>(null);const [form,setForm]=useState({customerName:'',customerEmail:'',customerPhone:''});const [error,setError]=useState('');const [loading,setLoading]=useState(false);
useEffect(()=>{fetch(`/api/public/businesses/${slug}`).then(async r=>{const d=await r.json();if(!r.ok){setError(d.error);return}setBusiness(d.business);setServices(d.services);if(d.services[0])setServiceId(d.services[0].id)})},[slug]);
useEffect(()=>{if(!serviceId||!date)return;setSelected(null);fetch(`/api/public/businesses/${slug}/availability?serviceId=${serviceId}&date=${date}`).then(async r=>{const d=await r.json();if(!r.ok){setError(d.error);setSlots([]);return}setError('');setSlots(d.slots||[])})},[serviceId,date,slug]);
const book=async(e:React.FormEvent)=>{e.preventDefault();if(!selected)return setError('Choose a time slot first');setLoading(true);setError('');const r=await fetch(`/api/public/businesses/${slug}/appointments`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,serviceId,startAt:selected.start})});const d=await r.json();if(!r.ok){setError(d.error);setLoading(false);return}router.push(`/booking/${d.appointment.bookingToken}`)};
if(error&&!business)return <main className="booking-shell"><div className="container"><div className="card"><h1>Booking unavailable</h1><p className="muted">{error}</p></div></div></main>;
return <main className="booking-shell"><div className="container"><div className="booking-header"><div className="row" style={{marginBottom:12}}><div className="small muted">BOOK AN APPOINTMENT</div><a className="btn btn-secondary" href="/customer/login">Customer portal</a></div><h1>{business?.name||'Loading…'}</h1><p className="muted">Choose a service, date and available time. Times are shown in {business?.timezone}.</p></div><div className="booking-grid"><section className="card"><h2 className="section-title">1. Choose a service</h2>{services.map(s=><button type="button" className={'service-option '+(serviceId===s.id?'selected':'')} key={s.id} onClick={()=>setServiceId(s.id)}><div className="row"><b>{s.name}</b><span className="small muted">{s.durationMin} min</span></div><div className="small muted" style={{marginTop:5}}>{s.description}</div></button>)}</section><section className="card"><h2 className="section-title">2. Pick a time</h2><div className="field"><label>Date</label><input type="date" min={new Date().toISOString().slice(0,10)} value={date} onChange={e=>setDate(e.target.value)}/></div>{date&&<><div className="small muted" style={{marginTop:18}}>Available slots</div><div className="slot-grid">{slots.map(s=><button type="button" key={s.start} className={'slot '+(selected?.start===s.start?'selected':'')} onClick={()=>setSelected(s)}>{s.label}</button>)}</div>{!slots.length&&<div className="empty">No available times for this date.</div>}</>}{error&&<div className="alert" style={{marginTop:16}}>{error}</div>}</section></div><form className="card stack" style={{marginTop:20}} onSubmit={book}><h2 className="section-title">3. Your details</h2><div className="form-grid"><div className="field"><label>Name</label><input required value={form.customerName} onChange={e=>setForm({...form,customerName:e.target.value})}/></div><div className="field"><label>Email</label><input required type="email" value={form.customerEmail} onChange={e=>setForm({...form,customerEmail:e.target.value})}/></div><div className="field"><label>Phone <span className="muted">(optional)</span></label><input value={form.customerPhone} onChange={e=>setForm({...form,customerPhone:e.target.value})}/></div></div><div className="row"><div className="muted small">{selected?`${selected.label} · ${services.find(s=>s.id===serviceId)?.name}`:'Select a slot above'}</div><button className="btn btn-primary" disabled={!selected||loading}>{loading?'Confirming…':'Confirm booking'}</button></div></form></div></main>}
